name = "status"
main = "src/index.js"
compatibility_date = "2024-12-01"

# API_KEY and SMTP2GO_API_KEY are set via `npx wrangler secret put <NAME>`

[vars]
ALERT_EMAILS = "system.user@jackross.co.uk"

[triggers]
crons = ["*/2 * * * *"]

[[d1_databases]]
binding = "status_monitor_db"
database_name = "status-monitor-db"
database_id = "d7efaaa1-02fa-4db6-9261-4a2831576d19"

